# Generated by Django 5.2.6 on 2025-09-14 10:59

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to=cinema.models.custom_image_path),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='movie_image',
            field=models.ImageField(null=True, upload_to=cinema.models.custom_image_path),
        ),
    ]
