# Generated by Django 5.2.6 on 2025-09-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_image_moviesession_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesession',
            name='movie_image',
        ),
    ]
